[tool.poetry]
name = "teddy"
version = "0.1.0"
description = ""
authors = ["min <han_thesis@naver.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
